spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image-upload
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  sql:
    init:
      mode: never
      data-locations: classpath:database/createDatabase.sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB